In [1]:
import pandas as pd
import numpy as np

In [2]:
# ---
df = pd.read_csv("survey.csv")
print("Shape:", df.shape)
df.head()

Shape: (1259, 27)

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [3]:
# ---
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Timestamp                  1259 non-null   str
 1   Age                        1259 non-null   int64
 2   Gender                     1259 non-null   str
 3   Country                    1259 non-null   str
 4   state                      744 non-null    str
 5   self_employed              1241 non-null   str
 6   family_history             1259 non-null   str
 7   treatment                  1259 non-null   str
 8   work_interfere             995 non-null    str
 9   no_employees               1259 non-null   str
 10  remote_work                1259 non-null   str
 11  tech_company               1259 non-null   str
 12  benefits                   1259 non-null   str
 13  care_options               1259 non-null   str
 14  wellness_program           1259 non-null   str
 15  seek_help                  1259 non-null   str
 16  anonymity                  1259 non-null   str
 17  leave                      1259 non-null   str
 18  mental_health_consequence  1259 non-null   str
 19  phys_health_consequence    1259 non-null   str
 20  coworkers                  1259 non-null   str
 21  supervisor                 1259 non-null   str
 22  mental_health_interview    1259 non-null   str
 23  phys_health_interview      1259 non-null   str
 24  mental_vs_physical         1259 non-null   str
 25  obs_consequence            1259 non-null   str
 26  comments                   164 non-null    str
dtypes: int64(1), str(26)
memory usage: 265.7 KB

In [4]:
# ---
df.columns.tolist()

['Timestamp',
 'Age',
 'Gender',
 'Country',
 'state',
 'self_employed',
 'family_history',
 'treatment',
 'work_interfere',
 'no_employees',
 'remote_work',
 'tech_company',
 'benefits',
 'care_options',
 'wellness_program',
 'seek_help',
 'anonymity',
 'leave',
 'mental_health_consequence',
 'phys_health_consequence',
 'coworkers',
 'supervisor',
 'mental_health_interview',
 'phys_health_interview',
 'mental_vs_physical',
 'obs_consequence',
 'comments']

In [5]:
# ---
df.isnull().sum()

Timestamp                       0
Age                             0
Gender                          0
Country                         0
state                         515
self_employed                  18
family_history                  0
treatment                       0
work_interfere                264
no_employees                    0
remote_work                     0
tech_company                    0
benefits                        0
care_options                    0
wellness_program                0
seek_help                       0
anonymity                       0
leave                           0
mental_health_consequence       0
phys_health_consequence         0
coworkers                       0
supervisor                      0
mental_health_interview         0
phys_health_interview           0
mental_vs_physical              0
obs_consequence                 0
comments                     1095
dtype: int64

In [6]:
# ---
df.duplicated().sum()

np.int64(0)

In [7]:
# Check unique values in important categorical columns
columns_to_check = [
    'Gender', 'self_employed', 'family_history', 'treatment', 'work_interfere',
    'remote_work', 'tech_company', 'benefits', 'care_options', 'wellness_program',
    'seek_help', 'anonymity', 'leave', 'mental_health_consequence',
    'phys_health_consequence', 'coworkers', 'supervisor', 'mental_health_interview',
    'phys_health_interview', 'mental_vs_physical', 'obs_consequence'
]
for col in columns_to_check:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Gender ---
Gender
Male                                              615
male                                              206
Female                                            121
M                                                 116
female                                             62
F                                                  38
m                                                  34
f                                                  15
Make                                                4
Woman                                               3
Male                                                3
Cis Male                                            2
Female                                              2
Man                                                 2
Female (trans)                                      2
Male-ish                                            1
maile                                               1
Trans-female                                        1
Cis Female                                          1
something kinda male?                               1
Mal                                                 1
Male (CIS)                                          1
queer/she/they                                      1
non-binary                                          1
Femake                                              1
woman                                               1
Nah                                                 1
All                                                 1
Enby                                                1
fluid                                               1
Genderqueer                                         1
Androgyne                                           1
Agender                                             1
cis-female/femme                                    1
Guy (-ish) ^_^                                      1
male leaning androgynous                            1
Trans woman                                         1
msle                                                1
Neuter                                              1
queer                                               1
Female (cis)                                        1
Mail                                                1
cis male                                            1
A little about you                                  1
Malr                                                1
p                                                   1
femail                                              1
Cis Man                                             1
ostensibly male, unsure what that really means      1
Name: count, dtype: int64

--- self_employed ---
self_employed
No     1095
Yes     146
NaN      18
Name: count, dtype: int64

--- family_history ---
family_history
No     767
Yes    492
Name: count, dtype: int64

--- treatment ---
treatment
Yes    637
No     622
Name: count, dtype: int64

--- work_interfere ---
work_interfere
Sometimes    465
NaN          264
Never        213
Rarely       173
Often        144
Name: count, dtype: int64

--- remote_work ---
remote_work
No     883
Yes    376
Name: count, dtype: int64

--- tech_company ---
tech_company
Yes    1031
No      228
Name: count, dtype: int64

--- benefits ---
benefits
Yes           477
Don't know    408
No            374
Name: count, dtype: int64

--- care_options ---
care_options
No          501
Yes         444
Not sure    314
Name: count, dtype: int64

--- wellness_program ---
wellness_program
No            842
Yes           229
Don't know    188
Name: count, dtype: int64

--- seek_help ---
seek_help
No            646
Don't know    363
Yes           250
Name: count, dtype: int64

--- anonymity ---
anonymity
Don't know    819
Yes           375
No             65
Name: count, dtype: int64

--- leave ---
leave
Don't know            563
Somewhat easy         266
Very easy             206
Somewhat difficult    126
Very difficult         98
Name: count, dtype: int64

--- mental_health_consequence ---
mental_health_consequence
No       490
Maybe    477
Yes      292
Name: count, dtype: int64

--- phys_health_consequence ---
phys_health_consequence
No       925
Maybe    273
Yes       61
Name: count, dtype: int64

--- coworkers ---
coworkers
Some of them    774
No              260
Yes             225
Name: count, dtype: int64

--- supervisor ---
supervisor
Yes             516
No              393
Some of them    350
Name: count, dtype: int64

--- mental_health_interview ---
mental_health_interview
No       1008
Maybe     207
Yes        44
Name: count, dtype: int64

--- phys_health_interview ---
phys_health_interview
Maybe    557
No       500
Yes      202
Name: count, dtype: int64

--- mental_vs_physical ---
mental_vs_physical
Don't know    576
Yes           343
No            340
Name: count, dtype: int64

--- obs_consequence ---
obs_consequence
No     1075
Yes     184
Name: count, dtype: int64

In [8]:
# ---
df['Age'].describe()

count    1.259000e+03
mean     7.942815e+07
std      2.818299e+09
min     -1.726000e+03
25%      2.700000e+01
50%      3.100000e+01
75%      3.600000e+01
max      1.000000e+11
Name: Age, dtype: float64

In [9]:
# ---
print("Unique ages:")
print(sorted(df['Age'].unique()))

Unique ages:
[np.int64(-1726), np.int64(-29), np.int64(-1), np.int64(5), np.int64(8), np.int64(11), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(60), np.int64(61), np.int64(62), np.int64(65), np.int64(72), np.int64(329), np.int64(99999999999)]

In [10]:
# ---
print("Number of countries:", df['Country'].nunique())
print("\nTop countries:")
print(df['Country'].value_counts().head(20))

Number of countries: 48

Top countries:
Country
United States     751
United Kingdom    185
Canada             72
Germany            45
Netherlands        27
Ireland            27
Australia          21
France             13
India              10
New Zealand         8
Switzerland         7
Poland              7
Italy               7
Sweden              7
Brazil              6
South Africa        6
Belgium             6
Israel              5
Bulgaria            4
Singapore           4
Name: count, dtype: int64

In [11]:
# ---
# Make a copy before cleaning
df_clean = df.copy()

In [12]:
# -----------------------------
# 1. Clean Age
# -----------------------------
# Ages outside a reasonable range are treated as missing
df_clean.loc[(df_clean['Age'] < 18) | (df_clean['Age'] > 100), 'Age'] = np.nan

In [13]:
# ---
# Fill invalid/missing ages with median age
df_clean['Age'] = df_clean['Age'].fillna(df_clean['Age'].median())

In [14]:
# ---
# Convert Age to integer
df_clean['Age'] = df_clean['Age'].astype(int)

In [15]:
# -----------------------------
# 2. Clean Gender  [FIXED]
# -----------------------------
male_set = {'m','male','male-ish','maile','mal','male (cis)','make','man',
            'msle','mail','malr','cis male','cis man','guy (-ish) ^_^',
            'male leaning androgynous'}
female_set = {'f','female','cis female','woman','femake','cis-female/femme',
              'female (cis)','femail'}

def clean_gender(value):
    value = str(value).strip().lower()
    if value in female_set:
        return 'Female'
    elif value in male_set:
        return 'Male'
    else:
        return 'Other'

df_clean['Gender'] = df_clean['Gender'].apply(clean_gender)

In [16]:
# -----------------------------
# 3. Convert Timestamp
# -----------------------------
df_clean['Timestamp'] = pd.to_datetime(df_clean['Timestamp'], errors='coerce')

In [18]:
# ---
# Check results
print("Age range:", df_clean['Age'].min(), "-", df_clean['Age'].max())
print("\nGender categories:")
print(df_clean['Gender'].value_counts())
print("\nMissing values after basic cleaning:")
print(df_clean.isnull().sum())

Age range: 18 - 72

Gender categories:
Gender
Male      993
Female    247
Other      19
Name: count, dtype: int64

Missing values after basic cleaning:
Timestamp                       0
Age                             0
Gender                          0
Country                         0
state                         515
self_employed                  18
family_history                  0
treatment                       0
work_interfere                264
no_employees                    0
remote_work                     0
tech_company                    0
benefits                        0
care_options                    0
wellness_program                0
seek_help                       0
anonymity                       0
leave                           0
mental_health_consequence       0
phys_health_consequence         0
coworkers                       0
supervisor                      0
mental_health_interview         0
phys_health_interview           0
mental_vs_physical              0
obs_consequence                 0
comments                     1095
dtype: int64

In [19]:
# ---
# Final missing-value treatment
df_clean['state'] = df_clean['state'].fillna('Not Specified')
df_clean['self_employed'] = df_clean['self_employed'].fillna('Unknown')
df_clean['work_interfere'] = df_clean['work_interfere'].fillna('Not Applicable')

In [20]:
# Comments has too many missing values and is not required for our structured EDA
df_clean.drop(columns=['comments'], inplace=True)

In [21]:
# Final checks
print("Shape after cleaning:", df_clean.shape)
print("\nRemaining missing values:")
print(df_clean.isnull().sum().sum())
print("\nData types:")
print(df_clean.dtypes)

Shape after cleaning: (1259, 26)

Remaining missing values:
0

Data types:
Timestamp                    datetime64[us]
Age                                   int64
Gender                                  str
Country                                 str
state                                   str
self_employed                           str
family_history                          str
treatment                               str
work_interfere                          str
no_employees                            str
remote_work                             str
tech_company                            str
benefits                                str
care_options                            str
wellness_program                        str
seek_help                               str
anonymity                               str
leave                                   str
mental_health_consequence               str
phys_health_consequence                 str
coworkers                               str
supervisor                              str
mental_health_interview                 str
phys_health_interview                   str
mental_vs_physical                      str
obs_consequence                         str
dtype: object

In [22]:
# Duplicate check  [FIXED - new cell]
# NOTE: every row has a unique Timestamp, so a duplicate check that
# includes Timestamp will always show 0. Check on the actual survey
# answers instead.
answer_cols = [c for c in df_clean.columns if c != 'Timestamp']
print("Duplicate rows (all columns incl. Timestamp):", df_clean.duplicated().sum())
print("Duplicate rows (survey answers only):", df_clean.duplicated(subset=answer_cols).sum())

df_clean = df_clean.drop_duplicates(subset=answer_cols).reset_index(drop=True)
print("Shape after removing duplicates:", df_clean.shape)

Duplicate rows (all columns incl. Timestamp): 0
Duplicate rows (survey answers only): 4
Shape after removing duplicates: (1255, 26)

In [23]:
# ---
df_clean.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,2014-08-27 11:29:31,37,Female,United States,IL,Unknown,No,Yes,Often,6-25,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,2014-08-27 11:29:37,44,Male,United States,IN,Unknown,No,No,Rarely,More than 1000,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,2014-08-27 11:29:44,32,Male,Canada,Not Specified,Unknown,No,No,Rarely,6-25,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,2014-08-27 11:29:46,31,Male,United Kingdom,Not Specified,Unknown,Yes,Yes,Often,26-100,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,2014-08-27 11:30:22,31,Male,United States,TX,Unknown,No,No,Never,100-500,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No

In [24]:
# ---
categorical_cols = df_clean.select_dtypes(include='object').columns
for col in categorical_cols:
    print(f"\n{col}:")
    print(df_clean[col].value_counts().head(15))

Gender:
Gender
Male      989
Female    247
Other      19
Name: count, dtype: int64

Country:
Country
United States     751
United Kingdom    184
Canada             72
Germany            45
Ireland            27
Netherlands        26
Australia          21
France             13
India              10
Switzerland         7
Poland              7
Italy               7
Sweden              7
New Zealand         7
Brazil              6
Name: count, dtype: int64

state:
state
Not Specified    511
CA               138
WA                70
NY                57
TN                45
TX                44
OH                30
IL                29
PA                29
OR                29
IN                27
MI                22
MN                21
MA                20
FL                15
Name: count, dtype: int64

self_employed:
self_employed
No         1092
Yes         145
Unknown      18
Name: count, dtype: int64

family_history:
family_history
No     765
Yes    490
Name: count, dtype: int64

treatment:
treatment
Yes    635
No     620
Name: count, dtype: int64

work_interfere:
work_interfere
Sometimes         465
Not Applicable    263
Never             213
Rarely            171
Often             143
Name: count, dtype: int64

no_employees:
no_employees
6-25              288
26-100            288
More than 1000    282
100-500           176
1-5               161
500-1000           60
Name: count, dtype: int64

remote_work:
remote_work
No     879
Yes    376
Name: count, dtype: int64

tech_company:
tech_company
Yes    1028
No      227
Name: count, dtype: int64

benefits:
benefits
Yes           477
Don't know    408
No            370
Name: count, dtype: int64

care_options:
care_options
No          500
Yes         442
Not sure    313
Name: count, dtype: int64

wellness_program:
wellness_program
No            839
Yes           228
Don't know    188
Name: count, dtype: int64

seek_help:
seek_help
No            643
Don't know    363
Yes           249
Name: count, dtype: int64

anonymity:
anonymity
Don't know    817
Yes           375
No             63
Name: count, dtype: int64

leave:
leave
Don't know            562
Somewhat easy         264
Very easy             206
Somewhat difficult    125
Very difficult         98
Name: count, dtype: int64

mental_health_consequence:
mental_health_consequence
No       489
Maybe    476
Yes      290
Name: count, dtype: int64

phys_health_consequence:
phys_health_consequence
No       923
Maybe    271
Yes       61
Name: count, dtype: int64

coworkers:
coworkers
Some of them    771
No              259
Yes             225
Name: count, dtype: int64

supervisor:
supervisor
Yes             516
No              391
Some of them    348
Name: count, dtype: int64

mental_health_interview:
mental_health_interview
No       1005
Maybe     206
Yes        44
Name: count, dtype: int64

phys_health_interview:
phys_health_interview
Maybe    556
No       498
Yes      201
Name: count, dtype: int64

mental_vs_physical:
mental_vs_physical
Don't know    575
Yes           342
No            338
Name: count, dtype: int64

obs_consequence:
obs_consequence
No     1072
Yes     183
Name: count, dtype: int64

C:\Users\user\AppData\Local\Temp\ipykernel_2948\3778253258.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df_clean.select_dtypes(include='object').columns

In [25]:
# ---
print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])
print("\nMissing values:", df_clean.isnull().sum().sum())
print("Duplicate rows:", df_clean.duplicated().sum())
print("Duplicate columns:", df_clean.columns.duplicated().sum())
print("\nAge range:", df_clean['Age'].min(), "-", df_clean['Age'].max())
print("\nGender categories:")
print(df_clean['Gender'].unique())
print("\nData types:")
print(df_clean.dtypes)

Rows: 1255
Columns: 26

Missing values: 0
Duplicate rows: 0
Duplicate columns: 0

Age range: 18 - 72

Gender categories:
<StringArray>
['Female', 'Male', 'Other']
Length: 3, dtype: str

Data types:
Timestamp                    datetime64[us]
Age                                   int64
Gender                                  str
Country                                 str
state                                   str
self_employed                           str
family_history                          str
treatment                               str
work_interfere                          str
no_employees                            str
remote_work                             str
tech_company                            str
benefits                                str
care_options                            str
wellness_program                        str
seek_help                               str
anonymity                               str
leave                                   str
mental_health_consequence               str
phys_health_consequence                 str
coworkers                               str
supervisor                              str
mental_health_interview                 str
phys_health_interview                   str
mental_vs_physical                      str
obs_consequence                         str
dtype: object

In [26]:
# ---
# Check actual column names
print("Actual column names:")
print(df.columns.tolist())
print("\nColumns with extra spaces:")
print([col for col in df.columns if col != col.strip()])
print("\nDuplicate column names:")
print(df.columns[df.columns.duplicated()].tolist())

Actual column names:
['Timestamp', 'Age', 'Gender', 'Country', 'state', 'self_employed', 'family_history', 'treatment', 'work_interfere', 'no_employees', 'remote_work', 'tech_company', 'benefits', 'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave', 'mental_health_consequence', 'phys_health_consequence', 'coworkers', 'supervisor', 'mental_health_interview', 'phys_health_interview', 'mental_vs_physical', 'obs_consequence', 'comments']

Columns with extra spaces:
[]

Duplicate column names:
[]

In [27]:
# ---
# Remove accidental spaces from column names
df_clean.columns = df_clean.columns.str.strip()

In [28]:
# [FIXED] Keep snake_case (not renamed to Title Case), stays compatible
# with app.py / the EDA notebook (columns like 'family_history', etc.)
print(df_clean.columns.tolist())

['Timestamp', 'Age', 'Gender', 'Country', 'state', 'self_employed', 'family_history', 'treatment', 'work_interfere', 'no_employees', 'remote_work', 'tech_company', 'benefits', 'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave', 'mental_health_consequence', 'phys_health_consequence', 'coworkers', 'supervisor', 'mental_health_interview', 'phys_health_interview', 'mental_vs_physical', 'obs_consequence']

In [29]:
# ---
# FINAL DATA CLEANING VALIDATION
print("===== DATASET STRUCTURE =====")
print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])
print("\n===== COLUMN NAMES =====")
print(df_clean.columns.tolist())
print("\n===== DUPLICATE COLUMNS =====")
print(df_clean.columns[df_clean.columns.duplicated()].tolist())
print("\n===== MISSING VALUES =====")
print("Total missing values:", df_clean.isnull().sum().sum())
print("\n===== DUPLICATE ROWS =====")
print("Duplicate rows:", df_clean.duplicated().sum())
print("\n===== AGE VALIDATION =====")
print("Minimum age:", df_clean['Age'].min())
print("Maximum age:", df_clean['Age'].max())
print("\n===== GENDER VALIDATION =====")
print(df_clean['Gender'].value_counts())
print("\n===== TIMESTAMP VALIDATION =====")
print("Invalid timestamps:", df_clean['Timestamp'].isna().sum())
print("\n===== DATA TYPES =====")
print(df_clean.dtypes)

===== DATASET STRUCTURE =====
Rows: 1255
Columns: 26

===== COLUMN NAMES =====
['Timestamp', 'Age', 'Gender', 'Country', 'state', 'self_employed', 'family_history', 'treatment', 'work_interfere', 'no_employees', 'remote_work', 'tech_company', 'benefits', 'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave', 'mental_health_consequence', 'phys_health_consequence', 'coworkers', 'supervisor', 'mental_health_interview', 'phys_health_interview', 'mental_vs_physical', 'obs_consequence']

===== DUPLICATE COLUMNS =====
[]

===== MISSING VALUES =====
Total missing values: 0

===== DUPLICATE ROWS =====
Duplicate rows: 0

===== AGE VALIDATION =====
Minimum age: 18
Maximum age: 72

===== GENDER VALIDATION =====
Gender
Male      989
Female    247
Other      19
Name: count, dtype: int64

===== TIMESTAMP VALIDATION =====
Invalid timestamps: 0

===== DATA TYPES =====
Timestamp                    datetime64[us]
Age                                   int64
Gender                                  str
Country                                 str
state                                   str
self_employed                           str
family_history                          str
treatment                               str
work_interfere                          str
no_employees                            str
remote_work                             str
tech_company                            str
benefits                                str
care_options                            str
wellness_program                        str
seek_help                               str
anonymity                               str
leave                                   str
mental_health_consequence               str
phys_health_consequence                 str
coworkers                               str
supervisor                              str
mental_health_interview                 str
phys_health_interview                   str
mental_vs_physical                      str
obs_consequence                         str
dtype: object

In [30]:
df_readable = df_clean.copy()
df_readable.columns = [c.replace('_', ' ').title() for c in df_readable.columns]
df_readable.to_csv("cleaned_survey_readable.csv", index=False)